In [ ]:
# start with pandas and numpy

In [2]:
import pandas as pd
import numpy as np

In [3]:
# import the data set
data1 =  pd.read_csv("C:\\Users\\Manohar Kapse\\PyCaret\\Pycaret Self Video\\1. Session\\happiness_report revised.csv")

In [4]:
data1.head()

,SNO,Country or region,Happyness_Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Region,Income group,Happiness_Group
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393,Europe & Central Asia,High income,high_score
1,2,Denmark,7.600,NaN,1.573,0.996,0.592,0.252,0.410,Europe & Central Asia,High income,high_score
2,3,Norway,7.554,1.488,NaN,1.028,0.603,0.271,0.341,Europe & Central Asia,High income,high_score
3,4,Iceland,7.494,1.380,1.624,NaN,0.591,0.354,0.118,Europe & Central Asia,High income,high_score
4,5,Netherlands,7.488,1.396,1.522,0.999,NaN,0.322,0.298,Europe & Central Asia,High income,high_score

In [5]:
from pycaret import *

In [5]:
### https://pycaret.gitbook.io/docs/

In [6]:
from pycaret.regression import *

In [10]:
# start regression with 
# RegressionExperiment
reg_exp = RegressionExperiment()

In [26]:
# Basic setup
# Step 1
reg_exp1 = reg_exp.setup(data=data1, target="Happyness_Score",
                        numeric_features=["GDP per capita",
                                          "Social support",
                                          "Healthy life expectancy",
                                          "Freedom to make life choices",
                                          "Generosity",
                                          "Perceptions of corruption"],
                         ignore_features=["SNO",
                                          "Country or region",
                                          "Happiness_Group",
                                          "Region",
                                          "Income group"])

In [12]:
# create a specific model, say linear regression
regression1 = reg_exp1.create_model('lr')

In [13]:
#Study the output of the model
regression1.coef_

array([0.7279073, 1.1697228, 1.1377565, 1.2502377, 2.0387127, 0.5121567],
      dtype=float32)

In [14]:
regression1.feature_names_in_

array(['GDP per capita', 'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption'], dtype=object)

In [ ]:
# Evaluate the model

In [15]:
reg_exp1.evaluate_model(regression1)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [ ]:
# Topics Covered
    # interactive residual
    # heteroscadisticty: resiudual vs predicted
    # normality of residual {if wethink there is problem with residual analysis, 
    # use transformation or outliers}
    # cooks distance: use outlier detection methods
    # learning curve
    # Validation Curve # hyperparameters
    # manifold learning problem is unsupervised: 
    # it learns the high-dimensional structure of the data from the data itself, 
    # without the use of predetermined classifications.

In [16]:
reg_exp1.X_test.corr() # using correlation we can try to find multicollinearity

,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
GDP per capita,1.000000,0.742332,0.827079,0.437245,-0.064804,0.357357
Social support,0.742332,1.000000,0.761794,0.585526,-0.068176,0.329678
Healthy life expectancy,0.827079,0.761794,1.000000,0.434591,-0.011656,0.285707
Freedom to make life choices,0.437245,0.585526,0.434591,1.000000,0.290887,0.416738
Generosity,-0.064804,-0.068176,-0.011656,0.290887,1.000000,0.265490
Perceptions of corruption,0.357357,0.329678,0.285707,0.416738,0.265490,1.000000

In [21]:
# multicollinearity
reg_exp2 = reg_exp.setup(data=data1, target="Happyness_Score",
                        numeric_features=["GDP per capita",
                                          "Social support",
                                          "Healthy life expectancy",
                                          "Freedom to make life choices",
                                          "Generosity",
                                          "Perceptions of corruption"],
                        #categorical_features=["Region","Income group"],
                        ignore_features=["SNO","Country or region","Happiness_Group","Region","Income group"],
                        remove_multicollinearity=True,
                        multicollinearity_threshold=0.3)
# create a specific model, say linear regression
regression2 = reg_exp2.create_model('lr')

In [22]:
reg_exp2.evaluate_model(regression2)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [23]:
# outliers
reg_exp2 = reg_exp.setup(data=data1, target="Happyness_Score",
                        numeric_features=["GDP per capita",
                                          "Social support",
                                          "Healthy life expectancy",
                                          "Freedom to make life choices",
                                          "Generosity",
                                          "Perceptions of corruption"],
                        #categorical_features=["Region","Income group"],
                        ignore_features=["SNO","Country or region","Happiness_Group","Region","Income group"],
                        remove_multicollinearity=True,
                        multicollinearity_threshold=0.5, 
                         remove_outliers=True,
                        outliers_method='iforest')
# create a specific model, say linear regression
regression2 = reg_exp2.create_model('lr')

In [ ]:
#remove_outliers=True
#outliers_method=''

‘iforest’: Uses sklearn’s IsolationForest.
‘ee’: Uses sklearn’s EllipticEnvelope.
‘lof’: Uses sklearn’s LocalOutlierFactor.

In [24]:
# feature Selection
reg_exp2 = reg_exp.setup(data=data1, target="Happyness_Score",
                        numeric_features=["GDP per capita",
                                          "Social support",
                                          "Healthy life expectancy",
                                          "Freedom to make life choices",
                                          "Generosity",
                                          "Perceptions of corruption"],
                        #categorical_features=["Region","Income group"],
                        ignore_features=["SNO","Country or region","Happiness_Group","Region","Income group"],
                         feature_selection= True, feature_selection_method='univariate')
# create a specific model, say linear regression
regression2 = reg_exp2.create_model('lr')

In [ ]:
feature_selection: bool, default = False
When set to True, a subset of features is selected based on a feature importance score determined by feature_selection_estimator.
feature_selection_method: str, default = 'classic'
Algorithm for feature selection. Choose from:
'univariate': Uses sklearn's SelectKBest.
'classic': Uses sklearn's SelectFromModel.
'sequential': Uses sklearn's SequentialFeatureSelector.

In [ ]:
# Dash board creation for XAI

In [27]:
reg_exp1.dashboard(regression1, display_format='dash')
# click on the, Starting ExplainerDashboard on 
# http://10.25.112.104:8050, to get the dashboard

# inline can also be used
#dashboard(regression1, display_format='inline')

WARNING: For shap='linear', shap interaction values can unfortunately not be calculated!
Warning: shap values for shap.LinearExplainer get calculated against X_background, but paramater X_background=None, so using X instead
Generating self.shap_explainer = shap.LinearExplainer(modelX)...
Building ExplainerDashboard..
Detected notebook environment, consider setting mode='external', mode='inline' or mode='jupyterlab' to keep the notebook interactive while the dashboard is running...
For this type of model and model_output interactions don't work, so setting shap_interaction=False...
The explainer object has no decision_trees property. so setting decision_trees=False...
Generating layout...
Calculating shap values...
Calculating predictions...
Calculating residuals...
Calculating absolute residuals...
Calculating dependencies...
Calculating importances...
Reminder: you can store the explainer (including calculated dependencies) with explainer.dump('explainer.joblib') and reload with e.g. ClassifierExplainer.from_file('explainer.joblib')
Registering callbacks...
Starting ExplainerDashboard on http://192.168.1.5:8050

ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=8050): Max retries exceeded with url: /_alive_beba4879-8064-442c-a598-a49cfa42889b (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C294005400>: Failed to establish a new connection: [WinError 10049] The requested address is not valid in its context'))